language: go

go:
    - 1.x
    - tip

install:
    - go get -t -v ./...
    - go install -a -race std

script:
    - go tool vet -all .
    - go build ./...
    - go test -race -v ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
